spring.application.name=jpa
server.port=8080
# DATABASE
spring.datasource.url=jdbc:h2:./db_dev;MODE=MySQL
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
logging.level.org.hibernate.SQL:DEBUG
logging.level.org.hibernate.orm.jdbc.bind:TRACE
logging.level.org.hibernate.orm.jdbc.extract:TRACE
logging.level.org.springframework.transaction.interceptor:TRACE